<?php

/*Utilisez les codes PHP, HTML et CSS ci-dessous, 
utilisez une condition pour afficher les variables. 
Si le nombre est pair, affichez le dans un paragraphe qui a la classe red. 
S'il est impair affichez le dans un paragraphe qui a la classe blue.
*/

$number1 = 42;
$number2 = 33;

.red {
	color:red;
}

.blue {
	color:blue;
}

?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Exercice 2 echo</title>
		<link rel="stylesheet" href="style.css" />
	</head>
	<body>
		
	</body>
</html>



