<?php

/*Utilisez le code PHP et HTML ci-dessous 
pour faire une boucle qui affichera chacun des animaux au sein d'une liste non-ordonnée.
*/
$animals = ["Chat", "Chien", "Souris", "Lama"];

?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Exercice 3 echo</title>
	</head>
	<body>
		<?php
		foreach ($animals as $animal){
		    echo"<li>$animal</li>";
		}
		
		?>
	</body>
</html>


