<?php

/*Utilisez les codes PHP, HTML et CSS ci-dessous, 
utilisez une condition pour afficher les variables. 
Si le nombre est pair, affichez le dans un paragraphe qui a la classe red. 
S'il est impair affichez le dans un paragraphe qui a la classe blue.
*/

$number1 = 42;
$number2 = 33;

?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Exercice 2 echo</title>
		<link rel="stylesheet" href="style.css" />
	</head>
	<body>
	    <?php
	    
		if($number1 %2 == 0) {
		    echo "<p class='red'>Le nombre $number1 est pair</p>";
			}
		else {
			echo "<p class='blue'>Le nombre $number1 est impair</p>";
			}
		
		if($number2 %2 == 0) {
		    echo "<p class='red'>Le nombre $number2 est pair</p>";
			}
		else {
			echo "<p class='blue'>Le nombre $number2 est impair</p>";
			}
		
		?>
		
	</body>
</html>

<!-- OU :

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Exercice 2 echo</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <?php
            if($number1 %2 === 0)
            {
                ?>
                <p class="red"><?= $number1 ?></p>
                <?php
            }
            else
            {
                ?>
                <p class="blue"><?= $number1 ?></p>
                <?php
            }
        ?>
        <?php
        if($number2 %2 === 0)
        {
            ?>
            <p class="red"><?= $number2 ?></p>
            <?php
        }
        else
        {
            ?>
            <p class="blue"><?= $number2 ?></p>
            <?php
        }
        ?>
    </body>
</html>
-->



