<?php

/*En utilisant le code HTML et PHP suivant, 
utilisez echo ou <?= ?> pour faire en sorte d'afficher la variable $title 
dans le h1 de l'article et la variable $content dans le p de l'article.
*/


$title = "This is the title of the article";
$content = "Ths is the content of the article";

?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Exercice 1 echo</title>
	</head>
	<body>
		<article>
			<h1>
                <?php echo $title; ?>
			</h1>
			<p>
                <?= $content ?>
			</p>
		</article>
	</body>
</html>



